export const BOOKS_ROWS = [
  {
    id: 0,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
  },
  {
    id: 1,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
  },
  {
    id: 2,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
  },
  {
    id: 3,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
  },
  {
    id: 4,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
  },
  {
    id: 5,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
  },
  {
    id: 6,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
  },
  {
    id: 7,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
  },
  {
    id: 8,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
  },
  {
    id: 9,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
  },
  {
    id: 10,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
  },
  {
    id: 11,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
  },
  {
    id: 12,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
  },
  {
    id: 13,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
  },
];

export const BOOKS_COLUMNS = [
  { field: "id", headerName: "ID", hide: true },
  { field: "title", headerName: "Book Title", sortable: false, flex: 1 },
  { field: "category", headerName: "Book Category", sortable: false, flex: 1 },
  { field: "author", headerName: "Book Author", sortable: false, flex: 1 },
  { field: "isbn", headerName: "Book ISBN", sortable: false, flex: 1 },
  { field: "version", headerName: "Book Version", sortable: false, flex: 1.5 },
  { field: "actions", headerName: "Actions", sortable: false, flex: 1.5 },
];
