import dayjs from "dayjs";
import { GridColDef } from "@mui/x-data-grid";

// TODO This fake books JSON list should be a BE request to fetch all the books
export const BOOKS_ROWS = [
  {
    id: 0,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First Edition",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief description",
  },
  {
    id: 1,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 2,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 3,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 4,
    title: "test book",
    category: "First Category",
    author: "admin",
    isbn: "23424232324",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 5,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 6,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 7,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 8,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 9,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 10,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 11,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 12,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
  {
    id: 13,
    title: "Design Patterns",
    category: "Second Category",
    author: "nouran",
    isbn: "090999090097",
    version: "1",
    price: "16",
    olderVersion: "2",
    edition: "First",
    releaseDate: dayjs(),
    coverImage: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    brief: "This is a sample brief",
  },
];

export const BOOKS_COLUMNS: GridColDef[] = [
  { field: "title", headerName: "Book Title", sortable: false, flex: 1 },
  { field: "category", headerName: "Book Category", sortable: false, flex: 1 },
  { field: "author", headerName: "Book Author", sortable: false, flex: 1 },
  { field: "isbn", headerName: "Book ISBN", sortable: false, flex: 1 },
  { field: "version", headerName: "Book Version", sortable: false, flex: 1 },
  {
    field: "actions",
    headerName: "Actions",
    sortable: false,
    flex: 0.5,
    headerAlign: "right",
    align: "right",
  },
];
